"""Atualizado modelo Cliente

Revision ID: 52aaec6f24e6
Revises: c11855de79ad
Create Date: 2023-12-20 02:16:51.349854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52aaec6f24e6'
down_revision = 'c11855de79ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('porte',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_endereco', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_endereco', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('numero_endereco')
        batch_op.drop_column('tipo_endereco')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('porte',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
